Models/CheckedServer.cs
using System;
using System.Net.NetworkInformation;
using System.Text;

namespace STNDown.Models
{
    public class CheckedServer
    {
        public int ID { get; set; }
        public string Location { get; set; }
        public string Name { get; set; }

        public PingResult Check()
        {
            // Creates new ping
            Ping pingSender = new Ping();
            try
            {
                string data = "four";
                byte[] buffer = Encoding.ASCII.GetBytes(data);
                PingReply reply = pingSender.Send(this.Location, 5000, buffer);

                if (reply.Status == IPStatus.Success)
                {
                    Console.WriteLine("Address: {0}", reply.Address.ToString());
                    Console.WriteLine("RoundTrip time: {0}", reply.RoundtripTime);
                    Console.WriteLine("Time to live: {0}", reply.Options.Ttl);
                    Console.WriteLine("Don't fragment: {0}", reply.Options.DontFragment);
                    Console.WriteLine("Buffer size: {0}", reply.Buffer.Length);
                    return new PingResult { Success = true };
                }
                else
                {
                    Console.WriteLine(reply.Status);
                    return new PingResult { Success = false };
                }
            }
            catch (PingException s)
            {
                return new PingResult { Success = false };
            }
        }
    }
}

Models/ErrorViewModel.cs
using System;

namespace STNDown.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/PingResult.cs
namespace STNDown.Models
{
    public class PingResult
    {
        public bool Success { get; set; }
    }
}

Controllers/CheckedServersController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using STNDown.Models;

namespace STNDown.Controllers
{
    public class CheckedServersController : Controller
    {
        private readonly STNDownContext _context;

        public CheckedServersController(STNDownContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> DoManualCheck(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var checkedServer = await _context.CheckedServer
                .SingleOrDefaultAsync(m => m.ID == id);
            if (checkedServer == null)
            {
                return NotFound();
            }

            var result = checkedServer.Check();

            return View(result);

        }

        

        
        public async Task<IActionResult> Index()
        {
            return View(await _context.CheckedServer.ToListAsync());
        }

         
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var checkedServer = await _context.CheckedServer
                .SingleOrDefaultAsync(m => m.ID == id);
            if (checkedServer == null)
            {
                return NotFound();
            }

            return View(checkedServer);
        }

        // GET: CheckedServers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: CheckedServers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Location,Name")] CheckedServer checkedServer)
        {
            if (ModelState.IsValid)
            {
                _context.Add(checkedServer);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(checkedServer);
        }

        // GET: CheckedServers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var checkedServer = await _context.CheckedServer.SingleOrDefaultAsync(m => m.ID == id);
            if (checkedServer == null)
            {
                return NotFound();
            }
            return View(checkedServer);
        }

        // POST: CheckedServers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Location,Name")] CheckedServer checkedServer)
        {
            if (id != checkedServer.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(checkedServer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CheckedServerExists(checkedServer.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(checkedServer);
        }

        // GET: CheckedServers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var checkedServer = await _context.CheckedServer
                .SingleOrDefaultAsync(m => m.ID == id);
            if (checkedServer == null)
            {
                return NotFound();
            }

            return View(checkedServer);
        }

        // POST: CheckedServers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var checkedServer = await _context.CheckedServer.SingleOrDefaultAsync(m => m.ID == id);
            _context.CheckedServer.Remove(checkedServer);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CheckedServerExists(int id)
        {
            return _context.CheckedServer.Any(e => e.ID == id);
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using STNDown.Models;

namespace STNDown.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "23/12/2017";

            return View();
        }


        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/CheckedServers/Create.cshtml
@model STNDown.Models.CheckedServer

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>CheckedServer</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Location" class="control-label"></label>
                <input asp-for="Location" class="form-control" />
                <span asp-validation-for="Location" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/CheckedServers/Delete.cshtml
@model STNDown.Models.CheckedServer

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CheckedServer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/CheckedServers/Details.cshtml
@model STNDown.Models.CheckedServer

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>CheckedServer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/CheckedServers/DoManualCheck.cshtml
@model STNDown.Models.PingResult

@{
    ViewData["Title"] = "DoManualCheck";
}

<h2>DoManualCheck</h2>

<p>@Model.Success</p>

Views/CheckedServers/Edit.cshtml
@model STNDown.Models.CheckedServer

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>CheckedServer</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Location" class="control-label"></label>
                <input asp-for="Location" class="form-control" />
                <span asp-validation-for="Location" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/CheckedServers/Index.cshtml
@model IEnumerable<STNDown.Models.CheckedServer>

@{
    ViewData["Title"] = "Manual Check Page";
}

<h2>Manual Checkup</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>

@if (Model.All(p => p.Check().Success))
{
    <h3 class="text-success">Every server is online :)</h3>
}
else if (Model.Any(p => p.Check().Success))
{
    <h3 class="text-danger">Warning! Problems at STN</h3>
    <h4>
        Please refer to the #announcements on discord for more infomation
    </h4>
}
else
{
    <h3 class="text-danger">Major problems at STN!!</h3>
    <h4>
        Please refer to the #announcements on discord for more infomation
    </h4>

}

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Location)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Location)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @if (item.Check().Success)
                    {
                        <span class="label label-success">Online</span>

                    }
                    else
                    {
                        <span class="label label-danger">Offline</span>
                    }
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.ID">Delete |</a>
                    <a asp-action="DoManualCheck" asp-route-id="@item.ID">Manual Check</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>This website was made by EvolveAir (Senpai#9422 on discord) and was a small time project for players to easily check uptime and downtime of STN's servers</p>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}


<h1>
    Is Survive the nights down?
</h1>
<center>
    <h3>
        Survive the nights is online at 
    </h3>
    <p>
        
    </p>

</center>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - STNDown</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">STNDown</a>
                <a asp-area="" asp-controller="CheckedServers" asp-action="Index" class="navbar-brand">Manual Check</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - STNDown</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>